SELECT
    DATE_FORMAT(ivb.DTHR_ITEM_VENDABALCAO, '%d/%m/%Y') AS DATA_VENDA,
    cp.CODIGO AS PRODUTO_CODIGO,
    ivb.DESCRICAO_PRODUTO AS PRODUTO, 
    ROUND(SUM(ivb.QUANTIDADE), 2) AS QUANTIDADE, 
    ROUND(AVG(ivb.UNITARIO), 2) AS VALOR_UNITARIO, 
    ROUND(SUM(ivb.TOTAL_ITEM_LIQUIDO_RATEIO), 2) AS TOTAL
FROM item_venda_balcao ivb 
LEFT JOIN produto p 
    ON ivb.ID_PRODUTO = p.ID_PRODUTO
LEFT JOIN codigo_produto cp 
    ON cp.ID_CODIGO_PRODUTO = p.ID_CODIGO_PRODUTO_PADRAO
WHERE DATE(ivb.DTHR_ITEM_VENDABALCAO) >= {{VALOR_DATA}}
GROUP BY 
    ivb.ID_PRODUTO,
    cp.CODIGO,
    ivb.DESCRICAO_PRODUTO,
    DATE(ivb.DTHR_ITEM_VENDABALCAO)
ORDER BY 
    DATE(ivb.DTHR_ITEM_VENDABALCAO) DESC,
    ivb.DESCRICAO_PRODUTO;
